### PR TITLE
Add Applications section allowing to apply as attendee or speaker

### PR DESCRIPTION
**Pull request by hugo-dc**

### CODE REVIEW

**Comment by hugo-dc** [comment]
> @Eni-G had an idea to make a separate section with these two butons

Any other content/text to add to this new separate section? @Eni-G

**Comment by Eni-G** [comment]
Yes, just add the following short sentence please:
If you are interested in attending the EVM Summit, or would like to give a talk or conduct a workshop, we encourage you to fill out the appropriate application form below.

The "Submit an Application" button in the "What to Expect at the Event" section could link to the "Applications" section.

**Comment by Eni-G** [comment]
Please add a separate "Applications" section after the "Who is this event directed to?" section (and add it to the menu bar as well) with the following short intro:

"If you are interested in attending the EVM Summit, or would like to give a talk or conduct a workshop, we encourage you to fill out the appropriate application form below."

And add two separate buttons with the appropriate links (already in PR): "Apply to Attend" and "Apply to Speak".

**Comment by hugo-dc** [comment]
Added a new *Applications* section.

**Review by gumb0 — APPROVED** [review]

**Pull request merged**
